version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql      
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "pass"
      POSTGRES_PORT: 5432
      POSTGRES_HOST: "0.0.0.0"
    ports:
      - "5432:5432"
  rssagregator:
    build: ./
    volumes:
      - ./:/rssAgregator
    ports:
      - "8585:8585"
    depends_on:
      - db
    links:
      - db



